import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SideNavigationBasic from "@/Components/Sidebar/index";
import React, { useState } from "react";
import Navbar from "@/Components/Navbar";
import Chatgptsidebar from "@/Components/Chatgptsidebar";
import MobileLayoutNavbar from "@/Components/MobileLayoutNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "First Next Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex">
          <div className="hidden md:block">
            <MobileLayoutNavbar />
          </div>
          <div className="flex-1">
             {children}
          </div>
        </div>
      </body>
    </html>
  );
}
